// This file was auto-generated by Fern from our API Definition.

import type * as plantstore from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const CreateMovieRequest: core.serialization.ObjectSchema<
    serializers.CreateMovieRequest.Raw,
    plantstore.CreateMovieRequest
> = core.serialization.object({
    title: core.serialization.string(),
    rating: core.serialization.number(),
});

export declare namespace CreateMovieRequest {
    export interface Raw {
        title: string;
        rating: number;
    }
}
