// This file was auto-generated by Fern from our API Definition.

import type * as plantstore from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const MovieId: core.serialization.Schema<serializers.MovieId.Raw, plantstore.MovieId> =
    core.serialization.string();

export declare namespace MovieId {
    export type Raw = string;
}
