// This file was auto-generated by Fern from our API Definition.

import { ImdbClient } from "./api/resources/imdb/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "./BaseClient.js";

export declare namespace plantstoreClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class plantstoreClient {
    protected readonly _options: NormalizedClientOptions<plantstoreClient.Options>;
    protected _imdb: ImdbClient | undefined;

    constructor(options: plantstoreClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    public get imdb(): ImdbClient {
        return (this._imdb ??= new ImdbClient(this._options));
    }
}
